title: Agha Chemsitry
email: s-mahmoud.agha@zewailcity.edu.eg
description: >- # this means to ignore newlines until "baseurl:"
  This site aims at providing chemical insights that are easy to understand
  through connected easy to understand yet state of the art information
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DevilishAgha
github_username:  psychodevil

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
    values:
      layout: "default"
